# Generated by Django 3.1.5 on 2021-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap2eat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfungu',
            name='acc_token',
            field=models.TextField(max_length=500),
        ),
    ]
